In [12]:
# Task 1

import numpy as np

a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [22]:
#Task 2

np.reshape(a, (12, 1))
np.reshape(a, (6, 2))
np.reshape(a, (4, 3))
np.reshape(a, (3, 4))
np.reshape(a, (2, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [30]:
# Task 3 

np.reshape(a, (12, -1))
np.reshape(a, (6, -1))
np.reshape(a, (4, -1))
np.reshape(a, (-1, 3))
np.reshape(a, (-1, 4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
# Task 4

b = np.reshape(a, (12, 1))
b[5]
print('Размерность у массива = 1')

Размерность у массива = 1


In [55]:
# Task 5

c = np.random.randn(3, 4)
if c.size == np.reshape(c, (1, -1)).size:
    print('True')
else:
    print('False')

True


In [62]:
# Task 6

a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [71]:
# Task 7

b = np.arange(20, 1, -2)
np.reshape(b, (1, 10))
print('Разница только в выдаче массива. В случае а - это кортеж. В случае b - кортеж в кортеже. А по сути и там и там одномерный массив')

Разница только в выдаче массива. В случае а - это кортеж. В случае b - кортеж в кортеже. А по сути и там и там одномерный массив


In [80]:
# Task 8

a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
if v.size == 10:
    print('True')
else:
    print('False')

True


In [106]:
# Task 9

a = np.arange(0, 12)
A = np.reshape(a, (4, 3))
At = A.T
B = A.dot(At)

print(f'Обратную матрицу вычислить не получится, потому что определить равен {np.linalg.det(B)}. Размер матрицы равен {B.size}')

Обратную матрицу вычислить не получится, потому что определить равен 0.0. Размер матрицы равен 16


In [128]:
# Task 10

np.random.seed(42)

a = np.random.rand(5)

np.random.seed(42)

b = np.random.rand(3)

a, b

(array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864]),
 array([0.37454012, 0.95071431, 0.73199394]))

In [136]:
# Task 11

a = np.arange(0, 16)

c = np.random.choice(a, 16, replace=False)
c

array([ 0,  5,  2, 14, 12,  7,  4, 10, 11,  9, 13, 15,  3,  1,  6,  8])

In [162]:
# Task 12

C = np.reshape(c, (4, 4))
C = C * 10
D = B + C


print(f'Определитель матрицы равен: {np.linalg.det(D)}')
print(f'Ранг матрицы равен: {np.linalg.matrix_rank(D)}')
print(f'Обратная матрица: {np.linalg.inv(D)}')

Определитель матрицы равен: -83972000.00000007
Ранг матрицы равен: 4
Обратная матрица: [[-0.01161101  0.01884676 -0.01498357  0.00847425]
 [ 0.02029939 -0.02462749  0.03876173 -0.03156004]
 [-0.00806888 -0.00684943  0.00654742  0.00140904]
 [ 0.00061544  0.0103282  -0.01562426  0.01114467]]


In [ ]:
# Task 13

